version: '3.1'
services:
  reactjs-frontend:
    container_name: reactjs_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    environment:
      REACT_APP_BASE_URL_BACKEND: 'http://localhost:7081/api/'
      REACT_APP_BACKEND_TOKEN: 'YXJxdWl0ZXR1cmFfY2dz'

    volumes:
      - ./frontend:/var/www/html
    ports:
      - 80:3000

networks:
  default:
    driver: bridge
